/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-05-08 10:17:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ksite.active.live;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.yoga.utils.Config;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/Users/yinluyinlu/ysh_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ysh_web/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/tld/tag.tld", Long.valueOf(1493898295000L));
    _jspx_dependants.put("jar:file:/Users/yinluyinlu/ysh_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ysh_web/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/Users/yinluyinlu/ysh_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ysh_web/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/views/ksite/active/live/../../../taglibs.jsp", Long.valueOf(1493898310000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1493898309000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.yoga.utils.Config");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no\">\n");
      out.write("<meta content=\"yes\" name=\"apple-mobile-web-app-capable\">\n");
      out.write("<meta content=\"yes\" name=\"apple-touch-fullscreen\">\n");
      out.write("<meta content=\"telephone=no,email=no\" name=\"format-detection\">\n");
      out.write("<title>随心瑜live</title>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/lib/setfontsize.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/sxy-live.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"app\">\n");
      out.write("\t\t<div class=\"stash\" id=\"stash\">\n");
      out.write("\t\t\t<span>拼命加载中，请稍候……</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--隐藏显示课件start-->\n");
      out.write("\t\t<div class=\"show-hide-courseware fixed flex\" id=\"showHideCourse\">\n");
      out.write("\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/show-hide-courseware.png\"\n");
      out.write("\t\t\t\talt=\"隐藏显示按钮\" class=\"icon\" /> <span class=\"text text1\">隐藏课件</span> <span\n");
      out.write("\t\t\t\tclass=\"none text text2\">显示课件</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--隐藏显示课件end-->\n");
      out.write("\t\t<!--视频播放区域start-->\n");
      out.write("\t\t<header class=\"video-box relative\" id=\"videoBox\">\n");
      out.write("\t\t\t<!--视频源-->\n");
      out.write("\t\t\t<video class=\"video absolute\" controls=\"controls\" id=\"video\">\n");
      out.write("\t\t\t\t<source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.filepath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("\t\t\t\t\ttype=\"audio/ogg\">\n");
      out.write("\t\t\t\t<source src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.filepath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("?v=2\"\n");
      out.write("\t\t\t\t\ttype=\"audio/ogg\">\n");
      out.write("\t\t\t</video>\n");
      out.write("\t\t\t<div class=\"video-palyer-box absolute removeVideoMask\"\n");
      out.write("\t\t\t\t@click=\"playVideo\">\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sxylive-banner.jpg\" alt=\"课程背景图\"\n");
      out.write("\t\t\t\t\tclass=\"video-img removeVideoMask\" /> <i\n");
      out.write("\t\t\t\t\tclass=\"icon video-play-btn \"></i>\n");
      out.write("\t\t\t\t<div class=\"mask\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!--视频播放区域end-->\n");
      out.write("\t\t<!--结束直播start-->\n");
      out.write("\t\t<div class=\"close-live-box fixed\" id=\"closeLive\" v-if=\"identity!=0\"\n");
      out.write("\t\t\t@click=\"closeLive\">\n");
      out.write("\t\t\t<div class=\"close-live flex\">\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sxy-live-close.png\" alt=\"\" />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<span>关闭直播</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--结束直播end-->\n");
      out.write("\t\t<!--在线人数start-->\n");
      out.write("\t\t<div class=\"online-box fixed\">\n");
      out.write("\t\t\t<i class=\"icon\"></i> <span class=\"text\"><b>0</b>人次</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--在线人数end-->\n");
      out.write("\t\t<!--操作按钮start-->\n");
      out.write("\t\t<div class=\"btn-broup-box fixed\" id=\"btnBroupBox\">\n");
      out.write("\t\t\t<span class=\"ask-size\">22222</span>\n");
      out.write("\t\t\t<div class=\"btn-box btn-box-ask\" id=\"btnBoxAsk\">\n");
      out.write("\t\t\t\t<button type=\"button\">\n");
      out.write("\t\t\t\t\t<div class=\"flex\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon\"></i>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<span class=\"text\">提问</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"btn-box btn-box-top\" id=\"btnBoxTop\">\n");
      out.write("\t\t\t\t<button type=\"button\">\n");
      out.write("\t\t\t\t\t<div class=\"flex\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon\"></i>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<span class=\"text\">顶部</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"btn-box btn-box-bottom\" id=\"btnBoxBottom\">\n");
      out.write("\t\t\t\t<button type=\"button\">\n");
      out.write("\t\t\t\t\t<div class=\"flex\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon\"></i>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<span class=\"text\">底部</span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--操作按钮end-->\n");
      out.write("\t\t<!--直播倒计时start-->\n");
      out.write("\t\t<div class=\"count-down-box flex\" id=\"countDownBox\">\n");
      out.write("\t\t\t<p>本次直播将于2017年3月18日 18：00开始</p>\n");
      out.write("\t\t\t<div class=\"count-down\">\n");
      out.write("\t\t\t\t<span class=\"day\">01</span>天<span class=\"hour\">11</span>时<span\n");
      out.write("\t\t\t\t\tclass=\"minutes\">01</span>分<span class=\"seconds\">45</span>秒\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--直播倒计时end-->\n");
      out.write("\t\t<!--导师消息start-->\n");
      out.write("\t\t<section class=\"teach-wrapper absolute\" id=\"mainBox\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li class=\"ls-zcr flex item\" v-for=\"(item,index) in datas\" v-if=\"item.status==1||item.status==2\">\n");
      out.write("\t\t\t\t<!-- 老师或管理员的普通消息 -->\n");
      out.write("\t\t\t\t\t<div class=\"flex\" v-if=\"item.isAsk==0\">\n");
      out.write("\t\t\t\t\t\t<!--头像-->\n");
      out.write("\t\t\t\t\t\t<div class=\"head-box\">\n");
      out.write("\t\t\t\t\t\t\t<img :src=\"item.userHeaderImg\" alt=\"\" class=\"head\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"border-box\">\n");
      out.write("\t\t\t\t\t\t\t<!--姓名和身份-->\n");
      out.write("\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"name\">{{item.userNickName}}</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"type-zcr type\" v-if=\"item.status == 1\">主持人</span>\n");
      out.write("\t\t\t\t\t\t\t\t <span class=\"type-ls type\" v-if=\"item.status == 2\">老师</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--消息-->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-box\" v-if=\"item.talkType==0\">{{item.content}}</div>\n");
      out.write("\t\t\t\t\t\t\t<!--语音-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"audio-btn-box\" v-if=\"item.talkType=='1'\">\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\"\n");
      out.write("\t\t\t\t\t\t\t\t\t:data-src=\"item.content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- 图片 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pic-box\" v-if=\"item.talkType=='2'\">\n");
      out.write("\t\t\t\t\t\t\t\t<img :src=\"item.content\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!--撤回按钮-->\n");
      out.write("\t\t\t\t\t\t<div class=\"chehui-btn\" data-id=\"1\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- 老师或管理员针对学员做的回复 -->\n");
      out.write("\t\t\t\t\t<div class=\"flex\" v-if=\"item.isAsk==1\">\n");
      out.write("\t\t\t\t\t<!--头像-->\n");
      out.write("\t\t\t\t\t<div class=\"head-box\">\n");
      out.write("\t\t\t\t\t\t<img :src=\"item.userHeaderImg\" alt=\"\" class=\"head\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"border-box\">\n");
      out.write("\t\t\t\t\t\t<!--姓名和身份-->\n");
      out.write("\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"name\">{{item.userNickName}}</h6>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"type-zcr type\" v-if=\"item.status == 1\">主持人</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"type-ls type\" v-if=\"item.status == 2\">老师</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!--回复内容主体-->\n");
      out.write("\t\t\t\t\t\t<div class=\"bj-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\" question-box flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon question-icon \"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<!--学员问的问题-->\n");
      out.write("\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"question-text-box flex \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"inline-block \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>{{item.content.userNickName}}：</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{{item.content.question}}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button \" class=\"answer-btn \"></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--老师回复消息主体-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"answer-msg-box flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon answer-icon \"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"audio-btn-box\" v-if=\"item.content.answer.type==2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t:data-src=\"item.content.answer.content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 文字回复 -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text-answer\" v-if=\"item.content.answer.type==0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-box\">{{item.content.answer.content}}</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t");
      out.write("</ul>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<!--导师消息start-->\n");
      out.write("\t\t<section class=\"all-msg-box absolute\" id=\"mainBox1\">\n");
      out.write("\t\t\t<header class=\"btn-group-box flex\" id=\"backGap\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn back\">回到直播</button>\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn gap\" v-if=\"identity!=0\">全员禁言</button>\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<nav id=\"tab\" class=\"tab relative\">\n");
      out.write("\t\t\t\t<ul class=\"flex\">\n");
      out.write("\t\t\t\t\t<li class=\"left curr\">全部</li>\n");
      out.write("\t\t\t\t\t<span>|</span>\n");
      out.write("\t\t\t\t\t<li class=\"right\">提问</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"bottom absolute curr\"></div>\n");
      out.write("\t\t\t\t<div class=\"none\"></div>\n");
      out.write("\t\t\t\t<div class=\"bottom1 absolute \"></div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<!--全部消息-->\n");
      out.write("\t\t\t<div class=\"answer-all-wrapper\">\n");
      out.write("\t\t\t\t<ul class=\"msg-box absolute \" id=\"allBoxAll\">\n");
      out.write("\t\t\t\t\t<li class=\"item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"question-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/a.png\" alt=\"\" class=\"head\" /> <span>大师兄</span>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"button icon answer-btn\"></button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"botton flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon question-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t四季的血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"question-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/a.png\" alt=\"\" class=\"head\" /> <span>大师兄</span>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"button icon answer-btn\"></button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"botton flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon question-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> <!--回复-->\n");
      out.write("\t\t\t\t\t\t<div class=\"answer-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/a.png\" alt=\"\" class=\"head\" />\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"name\">于是花</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"type-zcr type\">主持人</span> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"type-ls type\">老师</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--回复-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-box \">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon answer-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--文字回复-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--语音回复-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"audio-btn-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"audio-btn-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\" data-id=\"11\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<!--  提问-->\n");
      out.write("\t\t\t\t<ul class=\"msg-box absolute all-box-question\" id=\"allBoxQuestion\">\n");
      out.write("\t\t\t\t\t<li class=\"item\" v-for=\"(item,index) in datas\" v-if=\"item.isAsk\">\n");
      out.write("\t\t\t\t\t\t<div class=\"question-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img :src=\"item.userHeaderImg\" alt=\"\" class=\"head\" /> <span>{{item.userNickName}}</span>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"button icon answer-btn\" v-if=\"identity\" :data-content=\"item.content\" :data-nickname=\"item.nickname\"></button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"botton flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon question-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<p>{{item.content}}</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"question-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/a.png\" alt=\"\" class=\"head\" /> <span>大师兄</span>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"button icon answer-btn\" data-nickname=\"大师兄\"  data-content=\"四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气\"></button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"botton flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon question-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t\t四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。四季的瑜伽理疗，气血亏虚，失眠，颈肩痛等瑜伽理疗方案，以及一眼知健康的气色诊断。\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div> <!--回复-->\n");
      out.write("\t\t\t\t\t\t<div class=\"answer-box\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"top flex\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/a.png\" alt=\"\" class=\"head\" />\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"name\">于是花</h6>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"type-zcr type\">主持人</span> <span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"type-ls type\">老师</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!--回复-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-box \">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon answer-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--文字回复-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"flex text\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>大家好大家好</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--语音回复-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"audio-btn-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-src=\"http://wimg.keepyoga.com/2-1xiaoyuanyuan_clip.mp3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"audio-btn-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-src=\"http://wimg.keepyoga.com/11.7dinglun.mp3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"http://wimg.keepyoga.com/image/son.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"inline-block audio-time-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"cicle\"></i> <span class=\"audio-time\">21\"</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"chehui-btn\" data-id=\"33\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<!--禁言弹出框-->\n");
      out.write("\t\t<div class=\"start-gap-box\" id=\"startGapBox\" v-if=\"identity!=0\">\n");
      out.write("\t\t\t<div class=\"gap-box\">\n");
      out.write("\t\t\t\t<i class=\"icon close\"></i>\n");
      out.write("\t\t\t\t<h1 class=\"title\">全员禁言模式</h1>\n");
      out.write("\t\t\t\t<p>全员禁言后，全员不能提问</p>\n");
      out.write("\t\t\t\t<div class=\"flex group-box\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"cancel\">取消</button>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"ok\">确认</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--tips-->\n");
      out.write("\t\t<div id=\"tips\">\n");
      out.write("\t\t\t<div class=\"tips flex\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<h1>禁言成功</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t{{identity}}\n");
      out.write("\t\t<!--导师消息end-->\n");
      out.write("\t\t<!--学员发消息start-->\n");
      out.write("\t\t<footer class=\"student-ask-box fixed\" v-if=\"identity==0\">\n");
      out.write("\t\t\t<div class=\"student-box flex\" id=\"studentBox\">\n");
      out.write("\t\t\t\t<div class=\"input-box relative\" id=\"inputBox\">\n");
      out.write("\t\t\t\t\t<div class=\"input-text\" contenteditable=\"true\" id=\"inputText\"></div>\n");
      out.write("\t\t\t\t\t<p class=\"absolute placeholder\" id=\"placeholder\">提问或发表你的看法</p>\n");
      out.write("\t\t\t\t\t<div class=\"checked-ask flex absolute\" id=\"checkBox\">\n");
      out.write("\t\t\t\t\t\t<i class=\"icon\" :class=\"{checked:dataCheck}\"></i> <span class=\"text\">提问</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"enter-btn\" id=\"enterBtn\">发送</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!--老师输入框和发送语音宽start-->\n");
      out.write("\t\t<div class=\"nost-msg-box none\" id=\"teachAudioBox\">\n");
      out.write("\t\t\t<!--学员消息-->\n");
      out.write("\t\t\t<div class=\"st-msg-box\">\n");
      out.write("\t\t\t\t<span>{{questionNickname}}：</span>\n");
      out.write("\t\t\t\t{{questionContent}}\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--语音盒子-->\n");
      out.write("\t\t\t<div class=\"sed-audio-box\" id=\"sendAudioBox\">\n");
      out.write("\t\t\t\t<h1>松开手指，立即发送</h1>\n");
      out.write("\t\t\t\t<div class=\"flex djs-box\">\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sxy-live-djsl.png\" alt=\"\" />\n");
      out.write("\t\t\t\t\t<div class=\"djs\">\n");
      out.write("\t\t\t\t\t\t<span id=\"time\">0</span>s : 60s\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sxy-live-djsr.png\" alt=\"\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--录音按钮-->\n");
      out.write("\t\t\t\t<div class=\"keyframesBox\">\n");
      out.write("\t\t\t\t\t<div id=\"keyframes\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"start-audio-btn flex none\" id=\"recordBox\">\n");
      out.write("\t\t\t\t\t<div class=\"start-audio flex\">\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sxy-live-start-audio-btn.png\"\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--文字输入框-->\n");
      out.write("\t\t\t<footer class=\"student-ask-box none\" id=\"teachText\">\n");
      out.write("\t\t\t\t<div class=\"student-box flex\" id=\"studentBox\">\n");
      out.write("\t\t\t\t\t<div class=\"input-box relative\" id=\"inputBox\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-text\" contenteditable=\"true\" id=\"inputText\"></div>\n");
      out.write("\t\t\t\t\t\t<p class=\"absolute placeholder\" id=\"placeholder\">提问或发表你的看法</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"enter-btn\" id=\"enterBtn\">发送</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--老师输入框和发送语音宽end-->\n");
      out.write("\t\t<!--导师和管理员发消息start-->\n");
      out.write("\t\t<footer class=\"send-msg-box flex fixed\" id=\"teachSendBox\"\n");
      out.write("\t\t\tv-if=\"identity!==0\">\n");
      out.write("\t\t\t<div class=\"yy\">\n");
      out.write("\t\t\t\t<i class=\"icon\"></i> <span>语音</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"wz\">\n");
      out.write("\t\t\t\t<i class=\"icon\"></i> <span>文字</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"tp\">\n");
      out.write("\t\t\t\t<i class=\"icon\"></i> <span>图片</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!--导师和管理员发消息end-->\n");
      out.write("\t\t<!--audio-->\n");
      out.write("\t\t<audio>\n");
      out.write("\t\t\t<source :src=\"audioSrc\" type=\"audio/ogg\">\n");
      out.write("\t\t\t<source :src=\"audioSrc+'?v=1'\" type=\"audio/ogg\">\n");
      out.write("\t\t</audio>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/lib/fastclick.min.js \"></script>\n");
      out.write("\t<script src=\"http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"http://res.wx.qq.com/open/js/jweixin-1.0.0.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/lib/vue.min.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\n");
      out.write("\t\tvar jspS = {\n");
      out.write("\t\t\tctx:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\tuserid:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\tnickname:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\tpic:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.file_path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\troomid:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\tteacherids:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.teacherids}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("\t\t\tholderids:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.holderids}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modules/sxy-live.js \"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("version");
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue("20130306");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("wxid");
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue("wx10352e193b39e646");
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("cdn");
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(9,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue("http://wimg.keepyoga.com");
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("sulist");
      // /WEB-INF/views/ksite/active/live/../../../taglibs.jsp(10,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue("13065,13060");
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }
}
